CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE TABLE "ApplicationConfigurations" (
        "Id" integer NOT NULL DEFAULT 1,
        "TrashRetentionDays" integer,
        "ConsumeMaxImagePixels" integer,
        "ConsumeMaxFileSize" bigint,
        "OcrClean" boolean,
        "OcrCleanContinuously" boolean,
        "OcrOutputType" character varying(32),
        "OcrSkipAlreadyDone" boolean,
        "OcrLanguage" character varying(64),
        "DefaultOwnerId" integer,
        "Timezone" character varying(64),
        "UpdateCheckingEnabled" boolean,
        "PdfDpi" integer,
        "JpegQuality" integer,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ModifiedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_ApplicationConfigurations" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_ApplicationConfiguration_Singleton" CHECK ("Id" = 1)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE TABLE "Correspondents" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(256) NOT NULL,
        "Slug" character varying(256),
        "Match" character varying(256),
        "MatchingAlgorithm" integer NOT NULL,
        "IsInsensitive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ModifiedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_Correspondents" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE TABLE "CustomFields" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(256) NOT NULL,
        "Type" integer NOT NULL,
        "ExtraData" jsonb,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ModifiedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_CustomFields" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE TABLE "DocumentTypes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(256) NOT NULL,
        "Slug" character varying(256),
        "Match" character varying(256),
        "MatchingAlgorithm" integer NOT NULL,
        "IsInsensitive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ModifiedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_DocumentTypes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE TABLE "MailAccounts" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(256) NOT NULL,
        "ImapServer" character varying(512) NOT NULL,
        "ImapPort" integer NOT NULL,
        "Username" character varying(256),
        "Password" character varying(1024),
        "OauthId" character varying(128),
        "CreatedAt" timestamp with time zone NOT NULL,
        "ModifiedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_MailAccounts" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE TABLE "PaperlessTasks" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TaskId" character varying(128) NOT NULL,
        "Name" character varying(256),
        "Status" integer NOT NULL,
        "Acknowledged" boolean NOT NULL,
        "Done" timestamp with time zone,
        "Result" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ModifiedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_PaperlessTasks" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE TABLE "SavedViews" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(256) NOT NULL,
        "UserId" integer,
        "SortField" character varying(128),
        "SortReverse" boolean NOT NULL,
        "FilterRules" jsonb,
        "ShowInDashboard" boolean NOT NULL,
        "ShowInSidebar" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ModifiedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_SavedViews" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE TABLE "ShareLinkBundles" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Slug" character varying(128) NOT NULL,
        "Created" timestamp with time zone NOT NULL,
        "Expires" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ModifiedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_ShareLinkBundles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE TABLE "StoragePaths" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(256) NOT NULL,
        "Slug" character varying(256),
        "PathTemplate" character varying(1024),
        "Match" character varying(256),
        "MatchingAlgorithm" integer NOT NULL,
        "IsInsensitive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ModifiedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_StoragePaths" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE TABLE "Tags" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(256) NOT NULL,
        "Slug" character varying(256),
        "Color" character varying(7),
        "TextColor" character varying(7),
        "IsInboxTag" boolean NOT NULL,
        "Match" character varying(256),
        "MatchingAlgorithm" integer NOT NULL,
        "IsInsensitive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ModifiedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_Tags" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE TABLE "Workflows" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(256) NOT NULL,
        "Order" integer NOT NULL,
        "Enabled" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ModifiedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_Workflows" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE TABLE "Documents" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Title" character varying(256),
        "Content" text,
        "CorrespondentId" integer,
        "DocumentTypeId" integer,
        "Created" timestamp with time zone,
        "Added" timestamp with time zone NOT NULL,
        "Modified" timestamp with time zone NOT NULL,
        "Checksum" character varying(64),
        "ArchiveChecksum" character varying(64),
        "Filename" character varying(1024),
        "StoragePath" character varying(1024),
        "OwnerId" integer,
        "ArchiveSerialNumber" integer,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ModifiedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_Documents" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Documents_Correspondents_CorrespondentId" FOREIGN KEY ("CorrespondentId") REFERENCES "Correspondents" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Documents_DocumentTypes_DocumentTypeId" FOREIGN KEY ("DocumentTypeId") REFERENCES "DocumentTypes" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE TABLE "MailRules" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(256) NOT NULL,
        "AccountId" integer NOT NULL,
        "Folder" character varying(256),
        "FilterRules" jsonb,
        "ActionType" character varying(64) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ModifiedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_MailRules" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_MailRules_MailAccounts_AccountId" FOREIGN KEY ("AccountId") REFERENCES "MailAccounts" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE TABLE "WorkflowActions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Type" integer NOT NULL,
        "Order" integer NOT NULL,
        "WorkflowId" integer NOT NULL,
        "ActionParameters" jsonb,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ModifiedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_WorkflowActions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_WorkflowActions_Workflows_WorkflowId" FOREIGN KEY ("WorkflowId") REFERENCES "Workflows" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE TABLE "WorkflowTriggers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Type" integer NOT NULL,
        "WorkflowId" integer NOT NULL,
        "Match" character varying(256),
        "MatchingAlgorithm" integer NOT NULL,
        "IsInsensitive" boolean NOT NULL,
        "FilterRules" jsonb,
        "FilterPath" character varying(1024),
        "FilterFilename" character varying(256),
        "Sources" jsonb,
        "ScheduleOffsetDays" integer,
        "ScheduleIsRecurring" boolean NOT NULL,
        "ScheduleRecurringIntervalDays" integer,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ModifiedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_WorkflowTriggers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_WorkflowTriggers_Workflows_WorkflowId" FOREIGN KEY ("WorkflowId") REFERENCES "Workflows" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE TABLE "DocumentCustomFields" (
        "DocumentId" integer NOT NULL,
        "CustomFieldId" integer NOT NULL,
        "Value" text,
        CONSTRAINT "PK_DocumentCustomFields" PRIMARY KEY ("DocumentId", "CustomFieldId"),
        CONSTRAINT "FK_DocumentCustomFields_CustomFields_CustomFieldId" FOREIGN KEY ("CustomFieldId") REFERENCES "CustomFields" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_DocumentCustomFields_Documents_DocumentId" FOREIGN KEY ("DocumentId") REFERENCES "Documents" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE TABLE "DocumentTags" (
        "DocumentId" integer NOT NULL,
        "TagId" integer NOT NULL,
        CONSTRAINT "PK_DocumentTags" PRIMARY KEY ("DocumentId", "TagId"),
        CONSTRAINT "FK_DocumentTags_Documents_DocumentId" FOREIGN KEY ("DocumentId") REFERENCES "Documents" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_DocumentTags_Tags_TagId" FOREIGN KEY ("TagId") REFERENCES "Tags" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE TABLE "DocumentVersions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "DocumentId" integer NOT NULL,
        "VersionNumber" integer NOT NULL,
        "FileName" character varying(1024),
        "FileSize" bigint,
        "Timestamp" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_DocumentVersions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DocumentVersions_Documents_DocumentId" FOREIGN KEY ("DocumentId") REFERENCES "Documents" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE TABLE "ShareLinks" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "DocumentId" integer NOT NULL,
        "Slug" character varying(128) NOT NULL,
        "Created" timestamp with time zone NOT NULL,
        "Expires" timestamp with time zone,
        "FileVersion" integer NOT NULL,
        "ShareLinkBundleId" integer,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ModifiedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_ShareLinks" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ShareLinks_Documents_DocumentId" FOREIGN KEY ("DocumentId") REFERENCES "Documents" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ShareLinks_ShareLinkBundles_ShareLinkBundleId" FOREIGN KEY ("ShareLinkBundleId") REFERENCES "ShareLinkBundles" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE TABLE "ProcessedMails" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "MailRuleId" integer NOT NULL,
        "DocumentId" integer,
        "Status" character varying(32) NOT NULL,
        "Received" timestamp with time zone NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ModifiedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_ProcessedMails" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ProcessedMails_MailRules_MailRuleId" FOREIGN KEY ("MailRuleId") REFERENCES "MailRules" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Correspondents_Name" ON "Correspondents" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Correspondents_Slug" ON "Correspondents" ("Slug");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_CustomFields_Name" ON "CustomFields" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE INDEX "IX_DocumentCustomFields_CustomFieldId" ON "DocumentCustomFields" ("CustomFieldId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE INDEX "IX_Documents_Added" ON "Documents" ("Added");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Documents_ArchiveSerialNumber" ON "Documents" ("ArchiveSerialNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE INDEX "IX_Documents_Checksum" ON "Documents" ("Checksum");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE INDEX "IX_Documents_CorrespondentId" ON "Documents" ("CorrespondentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE INDEX "IX_Documents_Created" ON "Documents" ("Created");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE INDEX "IX_Documents_DocumentTypeId" ON "Documents" ("DocumentTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE INDEX "IX_DocumentTags_TagId" ON "DocumentTags" ("TagId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_DocumentTypes_Name" ON "DocumentTypes" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_DocumentTypes_Slug" ON "DocumentTypes" ("Slug");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_DocumentVersions_DocumentId_VersionNumber" ON "DocumentVersions" ("DocumentId", "VersionNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE INDEX "IX_MailAccounts_Name" ON "MailAccounts" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE INDEX "IX_MailRules_AccountId" ON "MailRules" ("AccountId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE INDEX "IX_PaperlessTasks_Status" ON "PaperlessTasks" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE INDEX "IX_PaperlessTasks_TaskId" ON "PaperlessTasks" ("TaskId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE INDEX "IX_ProcessedMails_MailRuleId" ON "ProcessedMails" ("MailRuleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE INDEX "IX_ProcessedMails_Status" ON "ProcessedMails" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE INDEX "IX_SavedViews_Name" ON "SavedViews" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_ShareLinkBundles_Slug" ON "ShareLinkBundles" ("Slug");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE INDEX "IX_ShareLinks_DocumentId" ON "ShareLinks" ("DocumentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE INDEX "IX_ShareLinks_ShareLinkBundleId" ON "ShareLinks" ("ShareLinkBundleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_ShareLinks_Slug" ON "ShareLinks" ("Slug");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_StoragePaths_Name" ON "StoragePaths" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_StoragePaths_Slug" ON "StoragePaths" ("Slug");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Tags_Name" ON "Tags" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Tags_Slug" ON "Tags" ("Slug");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE INDEX "IX_WorkflowActions_WorkflowId" ON "WorkflowActions" ("WorkflowId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE INDEX "IX_Workflows_Order" ON "Workflows" ("Order");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    CREATE INDEX "IX_WorkflowTriggers_WorkflowId" ON "WorkflowTriggers" ("WorkflowId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260627211719_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260627211719_InitialCreate', '10.0.0-preview.3.25171.6');
    END IF;
END $EF$;
COMMIT;

